### PR TITLE
Create testing

### PR DESCRIPTION
**Pull request by amitstein**

### CODE REVIEW

**Comment by jfatta** [comment]
A task has been created to review this pull request. You can view the task here: [SAMPLE-3632](https://azurecom.atlassian.net/browse/SAMPLE-3632)

Issues referenced by the commits in this pull request
- [SAMPLE-1893](https://azurecom.atlassian.net/browse/SAMPLE-1893)
- [SAMPLE-3565](https://azurecom.atlassian.net/browse/SAMPLE-3565)

**Comment by jfatta** [comment]
### Tests playlists

> see how to work with tests playlists [here](https://acomdocs.azure.net/documentation/process-testing-referencing-tests-with-prs-playlists/).

**Warning**: the pull request doesn’t include a list of tests to validate the changes.

**Comment by jfatta** [comment]
### Tests playlists

> see how to work with tests playlists [here](https://acomdocs.azure.net/documentation/process-testing-referencing-tests-with-prs-playlists/).

**Warning**: the pull request doesn’t include a list of tests to validate the changes.

**Comment by amitstein** [comment]
test comment

**Comment by amitstein** [comment]
comment 2

**Comment by amitstein** [comment]
comment 3

**Comment by amitstein** [comment]
comment 5

**Pull request closed without merging**
